CREATE TABLE Kino
( film VARCHAR(200) NOT NULL,
antall INTEGER NOT NULL,
fornavn VARCHAR(200) NOT NULL,
etternavn VARCHAR(200) NOT NULL,
telefon INTEGER NOT NULL,
epost VARCHAR(200) NOT NULL,
PRIMARY KEY (telefon));